export const skills = [
    "Semantic & accessible HTML",
    "Web fonts",
    "CSS BEM Convention",
    "CSS Grid",
    "CSS Selectors",
    "CSS Flexbox",
    "CSS grid",
    "Normalize.css",
    "Pseudoclasses",
    "Media Queries",
    "Responsive Web Design",
    "Alternative Box Model",
    "OpenGraph protocol",
    "NPM",
    "JavaScript(ES6+)",
    "Forms",
    "Objects",
    "Arrays",
    "Immutability",
    "Terminal",
    "GitHub",
    "Scrum",
    "Local Storage & Cookies",
    "Working with API", 
   //   [
   //      "XMLHttpRequest",
   //      "Fetch",
   //      "Axios (preferable)"
   //   ],
     "Promises, Async/Await",
     "React.js",
     "Hooks",
   //   [
   //      "useState",
   //      "useEffect",
   //      "useCurrent",
   //      "useRef",
   //      "useSelector",
   //      "useDispatch",
   //      "useParams",
   //      "useHistory",
   //      "useLocation",
   //      "custom hooks"
   //   ],
     "Console",
     "try/catch",
     "Error handling",
     "JSON",
     "Markdown",
     "Trello",
     "Figma",
     "React Router/Hash Router",
     "Git",
     "Git branching",
     "GitHub",
     "GitHub Pages",
     "Pull requests & code review",
     "Redux",
     "Creting slices for features",
     "Redux-Saga",
     "generators",
     "i18next & react-i18next"
]